# Generated by Django 6.0.2 on 2026-03-21 15:22

import django.db.models.deletion
import django.utils.timezone
import thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
                (
                    "show_home",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar en la home"
                    ),
                ),
                (
                    "project_img",
                    thumbnails.fields.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/images/",
                        verbose_name="Imagen del proyecto",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
