# Generated by Django 6.0.2 on 2026-03-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='show_home',
        ),
    ]
