# Generated by Django 6.0.2 on 2026-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectmodel_show_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['-order', '-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Orden'),
        ),
    ]
