# Generated by Django 6.0.2 on 2026-03-24 13:26

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='description',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Descripción'),
        ),
    ]
