# Generated by Django 6.0.2 on 2026-03-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='project_img',
        ),
    ]
