# Generated by Django 6.0.2 on 2026-03-07 18:27

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_img',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Portada del blog'),
        ),
    ]
