# Generated by Django 6.0.2 on 2026-03-23 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_contactado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='comentario',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre'),
        ),
    ]
