# Generated by Django 6.0.2 on 2026-03-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='toc',
            field=models.FileField(null=True, upload_to='courses/toc/', verbose_name='Temario'),
        ),
    ]
