# Generated by Django 6.0.2 on 2026-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='toc',
            field=models.FileField(blank=True, null=True, upload_to='courses/toc/', verbose_name='Temario'),
        ),
    ]
