# Generated by Django 6.0.2 on 2026-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?'),
        ),
    ]
